### PR TITLE
Additon of All Contributors | Issue #12

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added all the contributors in readme.md file to give them appreciation.
Completed #12 

image

@Shubham-Zone  please review and accept

### CODE REVIEW

**Comment by Shariq2003** [comment]
@Shubham-Zone please add level of gssco ext and also label of level to this PR.

**Comment by Shariq2003** [comment]
@Shubham-Zone please add gssoc label

**Comment by Shariq2003** [comment]
@MastanSayyad sir, sorry for disturbing again, but you just have to add labels, pleaseeeeeeee.

**Comment by MastanSayyad** [comment]
@Shubham-Zone dont have access to the repo, kindly review the PR and add me as a collabortaor

**Pull request merged**
